### ISSUE TITLE
Building on openSUSE Tumbleweed doesn't work

### ISSUE THREAD

**Issue by LorenDB** [adobe/XMP-Toolkit-SDK#52]
### Expected Behaviour
I anticipated a successful build.

### Actual Behaviour
Running `make` in `<xmpsdk>/build` produced the following output: https://gist.github.com/LorenDB/2e06077544a178250713cea50cb4bc45

#### Steps to Reproduce
1. Start an openSUSE VM or computer.
2. `git clone https://github.com/adobe/XMP-Toolkit-SDK.git`
3. `cd XMP-Toolkit-SDK/build`
4. `make`

#### Platform and Version
Latest openSUSE Tumbleweed with latest XMP SDK code

**Comment by maupadhyay** [comment]
Hi @LorenDB ,
It seems the issue you are facing is due to missing third-party source files. Please refer to third-party of [XMP Toolkit SDK Contents](https://github.com/adobe/XMP-Toolkit-SDK#xmp-toolkit-sdk-contents) section in readme. You need to download and place the third-party source before building.

**Comment by LorenDB** [comment]
Thanks, that indeed was the problem!
