### ISSUE TITLE
XMPFiles::GetXMP() removes attributes with empty string.

### ISSUE THREAD

**Issue by Mohammed-Javad** [adobe/XMP-Toolkit-SDK#72]
I have a png with Embedded xmp data as shown below

_<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 6.0.0">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:TMU="http://torontomu.ca/XMP/1.0/"
   TMU:action=""
   TMU:jobNumber=""
   TMU:userEmail=""
   TMU:userName=""/>
 </rdf:RDF>
</x:xmpmeta>_

And I am reading the embedded xmp using XMPFiles::GetXMP()

### Expected Behaviour
It should return the complete xmp.

### Actual Behaviour
It returns empty string because the attributes values are empty string.

#### Steps to Reproduce
1. Build the sample application ReadingXMP.exe.
2. create a Sample file with embedded xmp with attributes with empty string.
3. Run ReadingXMP.exe , pass Sample file as argument.
4. Observe that in the returned xmp the attributes with empty values are removed.

#### Platform and Version
Windows 10

**Comment by maupadhyay** [comment]
XMPFiles::GetXMP() internally calls [SXMPUtils::ApplyTemplate](https://github.com/adobe/XMP-Toolkit-SDK/blob/main/XMPCore/source/XMPUtils-FileInfo.cpp#L1541) where properties with empty values are either ignored or cause deletion. Hence the out xmpMeta object do not have empty values. This is expected behaviour.

In case you still need that packet 
`GetXMP ( SXMPMeta *       xmpObj = 0, tStringObj *     xmpPacket = 0,  XMP_PacketInfo * packetInfo = 0 );` https://github.com/adobe/XMP-Toolkit-SDK/blob/main/public/include/TXMPFiles.hpp#L627 can be called with non null string object in which it will return the raw XMP packet as stored in the file.
